"Bo1015/contact_prediction_binary": {"loss_type": "classification", "output_type": "residue", "num_labels": 2, "metric": "long_range_precision_at_L"}
"Bo1015/fold_prediction": {"loss_type": "classification", "output_type": "protein", "num_labels": 1195, "metric": "accuracy"}
"Bo1015/ssp_q3": {"loss_type": "classification", "output_type": "residue", "num_labels": 3, "metric": "accuracy"}
"Bo1015/solubility_prediction": {"loss_type": "classification", "output_type": "protein", "num_labels": 2, "metric": "accuracy"}
"Bo1015/stability_prediction": {"loss_type": "regression", "output_type": "protein", "num_labels": 1, "metric": "spearman"}
"Bo1015/temperature_stability": {"loss_type": "classification", "output_type": "protein", "num_labels": 2, "metric": "mcc"}
"Bo1015/optimal_temperature": {"loss_type": "regression", "output_type": "protein", "num_labels": 1, "metric": "srcc"}
"Bo1015/optimal_ph": {"loss_type": "regression", "output_type": "protein", "num_labels": 1, "metric": "srcc"}
"Bo1015/cloning_clf": {"loss_type": "classification", "output_type": "protein", "num_labels": 2, "metric": "auc"}
"Bo1015/material_production": {"loss_type": "classification", "output_type": "protein", "num_labels": 2, "metric": "auc"}
"Bo1015/metal_ion_binding": {"loss_type": "classification", "output_type": "protein", "num_labels": 2, "metric": "accuracy"}
"Bo1015/enzyme_catalytic_efficiency": {"loss_type": "regression", "output_type": "protein", "num_labels": 1, "metric": "pcc"}
"Bo1015/peptide_HLA_MHC_affinity": {"loss_type": "classification", "output_type": "protein", "num_labels": 2, "metric": "auc"}
"Bo1015/tcr_pmhc_affinity": {"loss_type": "classification", "output_type": "protein", "num_labels": 2, "metric": "auc"}
"Bo1015/antibiotic_resistance": {"loss_type": "classification", "output_type": "protein", "num_labels": 19, "metric": "accuracy"}
"Bo1015/fluorescence_prediction": {"loss_type": "regression", "output_type": "protein", "num_labels": 1, "metric": "spearman"}
"Bo1015/fitness_prediction": {"loss_type": "regression", "output_type": "protein", "num_labels": 1, "metric": "spearman"}
"Bo1015/localization_prediction": {"loss_type": "classification", "output_type": "protein", "num_labels": 10, "metric": "accuracy"}

"saprot_data/DeepLoc_cls10": {"loss_type": "classification", "output_type": "protein", "num_labels": 10, "metric": "accuracy"}
"saprot_data/DeepLoc_cls2": {"loss_type": "classification", "output_type": "protein", "num_labels": 2, "metric": "accuracy"}
"saprot_data/EC_AF2": {"loss_type": "multi_classification", "output_type": "protein", "num_labels": 585, "metric": "fmax"}
"saprot_data/GO_AF2_MF": {"loss_type": "multi_classification", "output_type": "protein", "num_labels": 489, "metric": "fmax"}
"saprot_data/GO_AF2_CC": {"loss_type": "multi_classification", "output_type": "protein", "num_labels": 320, "metric": "fmax"}
"saprot_data/GO_AF2_BP": {"loss_type": "multi_classification", "output_type": "protein", "num_labels": 1943, "metric": "fmax"}
"saprot_data/MetalIonBinding_AF2": {"loss_type": "classification", "output_type": "protein", "num_labels": 2, "metric": "accuracy"}
"saprot_data/Thermostability": {"loss_type": "regression", "output_type": "protein", "num_labels": 1, "metric": "spearman"}
"saprot_data/HumanPPI": {"loss_type": "classification", "output_type": "protein", "num_labels": 2, "metric": "accuracy"}
