data_path: /home/mila/s/shawn.whitfield/scratch/data/datasets/biomap-research/metal_ion_binding_processed.parquet.gz
dataset_name: biomap_metal_ion_binding
task_level: protein_level
task_type: binary_classification
