data_path: /home/mila/s/shawn.whitfield/scratch/data/datasets/h_sapiens_proteome/processed_subsets/go/h_sapiens_proteome_go_biological_process_clustersplit_20_50.parquet.gz
dataset_name: GO_bp
task_level: protein_level
task_type: binary_classification
