data_path: /home/mila/s/shawn.whitfield/scratch/data/datasets/h_sapiens_proteome/processed_subsets/uniprot_ann/h_sapiens_proteome_uniprot_secondary_structure_clustersplit_20_50_split1.parquet.gz
dataset_name: uniprot_secondary_structure_split1
task_level: amino_acid_level
task_type: multiclass_classification
