#!/bin/bash

# ====================================================================
# SLURM DIRECTIVES
# ====================================================================

#SBATCH --job-name=neighbor
#SBATCH --partition=long                          
#SBATCH --cpus-per-task=1
#SBATCH --mem=100G                             
#SBATCH --gres=gpu:0                                                    
#SBATCH --time=1:00:00     
#SBATCH -o /network/scratch/s/shawn.whitfield/logs/neighborhood/slurm-%A_%a.out 
#SBATCH -e /network/scratch/s/shawn.whitfield/logs/neighborhood/slurm-%A_%a.err 
#SBATCH --array=0-643

# ====================================================================
# CONFIGURATION
# ====================================================================

#0-73 all models, select layers, go_cc and active_site
#0-939 all datasets, every second layer, amplify and esm650
#0-351 all models, every second layer + end, conserved site and domain
#0-879 all models, every second layer + end, conserved_site to domain
#0-879 all models, every second layer + end, family to go
#0-643 all models, every layer, 2 datasets

TASK_ID=$SLURM_ARRAY_TASK_ID

# Configuration file generated by the Python script
CONFIG_FILE="nearest_neighbor_configs.txt"

# Assuming the config file is a simple list like:
# amplify_120m 0 interpro_active_site euclidean
CONFIG_LINE=$(sed -n "$((TASK_ID + 1))p" "$CONFIG_FILE")

# Set Internal Field Separator to space temporarily
IFS=' ' read -r MODEL_SHORTHAND LAYER_TO_USE TARGET_DATASET DISTANCE_METRIC <<< "$CONFIG_LINE"

# Error Check (Simplified)
if [ -z "$MODEL_SHORTHAND" ] || [ -z "$DISTANCE_METRIC" ]; then
    echo "ERROR: Configuration not found for task ID $TASK_ID. Array range may be incorrect."
    exit 1
fi

# Create a unique job name for this specific run
JOB_NAME="${TARGET_DATASET}_${MODEL_SHORTHAND}_layer_${LAYER_TO_USE}_${DISTANCE_METRIC}"

echo $JOB_NAME

# ====================================================================
# EXECUTION
# ====================================================================

echo "--- SLURM Array Task $TASK_ID: Running single job ---"
echo "Model Shorthand: $MODEL_SHORTHAND"
echo "Layer: $LAYER_TO_USE"
echo "Dataset: $TARGET_DATASET"
echo "Metric: $DISTANCE_METRIC"


# Run the script
uv run python3 test_neighborhood.py \
    plm_model.shorthand=$MODEL_SHORTHAND \
    plm_model.model_layer_num=$LAYER_TO_USE \
    knn.neighbor_ks=[1,3,5,7,11,17,21] \
    knn.distance_metric=$DISTANCE_METRIC \
    data.dataset_name=$TARGET_DATASET \
    
echo "--------------------------------------------------------"
echo "Task $TASK_ID finished."