#!/bin/bash

# ====================================================================
# SLURM DIRECTIVES
# ====================================================================

#SBATCH --job-name=neighbor
#SBATCH --partition=long                          
#SBATCH --cpus-per-task=1
#SBATCH --mem=25G                             
#SBATCH --gres=gpu:0                                                    
#SBATCH --time=10:00:00 
#SBATCH -o /network/scratch/s/shawn.whitfield/logs/neighborhood/slurm-%A_%a.out 
#SBATCH -e /network/scratch/s/shawn.whitfield/logs/neighborhood/slurm-%A_%a.err 

# We pack 10 jobs per index. 9660 total lines / 10 = 966 indices.
# This stays under your cluster MaxArraySize of 1001.
# %100 limits you to 100 active tasks (1000 total jobs running at once).
#SBATCH --array=0-966

# ====================================================================
# CONFIGURATION
# ====================================================================

# Configuration file generated by the Python script
CONFIG_FILE="nearest_neighbor_configs.txt"
JOBS_PER_INDEX=10

# Calculate the starting line for this specific array task
# Example: If ARRAY_ID is 1, START_INDEX is 10 (will process lines 11-20)
START_LINE_INDEX=$(( SLURM_ARRAY_TASK_ID * JOBS_PER_INDEX ))

# ====================================================================
# EXECUTION LOOP
# ====================================================================

echo "--- SLURM Array Task $SLURM_ARRAY_TASK_ID: Starting Batch of $JOBS_PER_INDEX ---"

for (( i=0; i<$JOBS_PER_INDEX; i++ )); do
    # Calculate the actual line number in the config file
    ACTUAL_LINE=$(( START_LINE_INDEX + i + 1 ))
    
    # Extract the configuration for this specific sub-job
    CONFIG_LINE=$(sed -n "${ACTUAL_LINE}p" "$CONFIG_FILE")

    # If the line is empty (end of file), stop the loop
    if [ -z "$CONFIG_LINE" ]; then
        echo "Line $ACTUAL_LINE is empty (End of File reached). Finishing task."
        break
    fi

    # Set Internal Field Separator to space temporarily and parse
    IFS=' ' read -r MODEL_SHORTHAND LAYER_TO_USE TARGET_DATASET DISTANCE_METRIC <<< "$CONFIG_LINE"

    # Error Check
    if [ -z "$MODEL_SHORTHAND" ] || [ -z "$DISTANCE_METRIC" ]; then
        echo "ERROR: Skip line $ACTUAL_LINE - Invalid configuration."
        continue
    fi

    # Create a unique job name for this specific run
    JOB_NAME="${TARGET_DATASET}_${MODEL_SHORTHAND}_layer_${LAYER_TO_USE}_${DISTANCE_METRIC}"

    echo "Sub-job $((i+1))/$JOBS_PER_INDEX (Line $ACTUAL_LINE): $JOB_NAME"

    # Run the script
    # We run this sequentially. When one finishes, the next starts in this task.
    uv run python3 test_neighborhood_split.py \
        paths.save_dir=/home/mila/s/shawn.whitfield/scratch/results/nearest_neighbor_splits \
        plm_model.shorthand=$MODEL_SHORTHAND \
        plm_model.model_layer_num=$LAYER_TO_USE \
        knn.neighbor_ks=[1,3,5,7,11,17,21] \
        knn.distance_metric=$DISTANCE_METRIC \
        data.dataset_name=$TARGET_DATASET

    echo "Completed Line $ACTUAL_LINE"
    echo "--------------------------------------------------------"
done

echo "Task $SLURM_ARRAY_TASK_ID finished all sub-jobs."