dir: /opt/ml/model/${now:%Y-%m-%d-%H-%M-%S}
resume: True
max_steps: 10
eval_steps: 1
save_steps: 1
max_checkpoints: 100
gradient_clipping: 1
gradient_accumulation_steps: 1 
tf32: True
disable_tqdm: False