#!/bin/bash

# ====================================================================
# SLURM DIRECTIVES
# ====================================================================

#SBATCH --job-name=probing
#SBATCH --partition=long                          
#SBATCH --cpus-per-task=1
#SBATCH --mem=48G                             
#SBATCH --gres=gpu:1                                                     
#SBATCH --time=36:00:00     
#SBATCH -o /network/scratch/s/shawn.whitfield/logs/linear_probing/slurm-%A_%a.out 
#SBATCH -e /network/scratch/s/shawn.whitfield/logs/linear_probing/slurm-%A_%a.err 
#SBATCH --array=0-11
#SBATCH --constraint=48gb

# ====================================================================
# CONFIGURATION
# ====================================================================

#0-683 AMPLIFY_120M and esm2_t12_35M_UR50D
#0-721 AMPLIFY_350M and esm2_t6_8M_UR50D
#0-626 esm2_t33_650M_UR50D
#0-607 saAMPLIFY350M
#0-569 esm2 150M
#0-455 SAMPLIFY120M
#0-607 AMPLIFY350M
#0-35 pparam amplify120m,esm35m
#0-684 normalization True all models, sspq8, peptide, domain, cc, topology
#0-385 all models uniprot lipidation phosphorylation
#0-192 all models biomap metal ion binding
#0-192 all models uniprot_domains
#0-192 all models interpro_homologous_superfamily
#0-239 all mila checkpoints, one dataset
#0-959 all mila checkpoints, four datasets
#0-791 all mila checkpoints, 3 datasets
#0-359 amplify120m, select datasets
#0-959 mila u50 checkpoints, four datasets

module load cudatoolkit/12.1

# Base output directory for all results
out_dir="/home/mila/s/shawn.whitfield/scratch/models/linear_probes/"

TASK_ID=$SLURM_ARRAY_TASK_ID

# Configuration file generated by the Python script
CONFIG_FILE="linear_probe_configs.txt"

CONFIG_LINE=$(sed -n "$((TASK_ID + 1))p" "$CONFIG_FILE")

# Use parameter expansion to strip the surrounding double quotes 
# from the model name before reading the fields.
MODEL_NAME_QUOTED="${CONFIG_LINE%% *}" # Extracts everything up to the first space (the quoted model name)
MODEL_NAME="${MODEL_NAME_QUOTED//\"}"  # Removes all double quotes
REMAINING_ARGS="${CONFIG_LINE#* }"      # Extracts the rest of the string (layer and dataset)
# Read the remaining arguments (layer and dataset) into an array
IFS=' ' read -r -a ARGS <<< "$REMAINING_ARGS"

# Map the arguments to meaningful variables
# MODEL_NAME is already clean from the step above
LAYER_TO_USE="${ARGS[0]}"
TARGET_DATASET="${ARGS[1]}"

# Error Check (Simplified)
if [ -z "$MODEL_NAME" ] || [ -z "$TARGET_DATASET" ]; then
    echo "ERROR: Configuration not found for task ID $TASK_ID. Array range may be incorrect."
    exit 1
fi

# Sanitize the full model path for use in filenames
sanitized_model_name="${MODEL_NAME//\//-}"
# Create a unique job name for this specific run
JOB_NAME="${TARGET_DATASET}_${sanitized_model_name}_layer_${LAYER_TO_USE}"

echo $JOB_NAME

# ====================================================================
# EXECUTION
# ====================================================================

echo "--- SLURM Array Task $TASK_ID: Running single job ---"
echo "Model: $MODEL_NAME ($sanitized_model_name)"
echo "Dataset: $TARGET_DATASET"
echo "Layer: $LAYER_TO_USE"
echo "Output Dir: $out_dir$JOB_NAME"

# Run the script
uv run python3 ../../main.py \
    hydra.job.name=$JOB_NAME \
    hydra.run.dir=$out_dir\${hydra.job.name}_normalized_\${algorithm.plm_config.normalize_embeddings} \
    experiment=linear_training \
    algorithm.plm_config.model_name=$MODEL_NAME \
    algorithm.plm_config.layer_to_use=$LAYER_TO_USE \
    algorithm.plm_config.normalize_embeddings=false \
    datamodule/dataset=$TARGET_DATASET \
    datamodule.num_workers=1 \
    trainer.logger.wandb.offline=true \
    trainer.logger.wandb.name=${TARGET_DATASET}_${sanitized_model_name}_layer_\${algorithm.plm_config.layer_to_use}_normalized_\${algorithm.plm_config.normalize_embeddings}
    
echo "--------------------------------------------------------"
echo "Task $TASK_ID finished."

